# Common application info
info.app.project=TradeFlow
info.app.config-source=github-config-server
management.info.env.enabled=true

management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.endpoint.health.show-details=always
management.info.env.enabled=true

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [correlationId=%X{correlationId:-N/A}] [traceId=%X{traceId:-N/A}] [spanId=%X{spanId:-N/A}] %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [correlationId=%X{correlationId:-N/A}] [traceId=%X{traceId:-N/A}] [spanId=%X{spanId:-N/A}] %logger{36} - %msg%n

# Trace 100% of requests. For local learning, we want every request to appear in Zipkin.
management.tracing.sampling.probability=1.0
#Send traces to Zipkin.
management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans
