info.app.name=reference-data-service
info.app.description=Reference data service config loaded from GitHub Config Repo
info.app.version=1.0.0

server.port=8082

spring.datasource.url=jdbc:h2:mem:reference_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always

eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}

logging.file.name=C:/tradeflow-workspace/logs/reference-data-service.log

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9091/realms/tradeflow
