info.app.name=trade-service
info.app.description=Trade service config loaded from GitHub Config Repo
info.app.version=1.0.0
tradeflow.config.message=Trade service message from GitHub

management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents,prometheus,refresh

server.port=8081

spring.datasource.url=jdbc:h2:mem:trade_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

reference-data-service.base-url=http://reference-data-service

logging.file.name=C:/tradeflow-workspace/logs/trade-service.log
logging.level.io.github.resilience4j=DEBUG

# Circuit breaker configuration for reference-data-service call
resilience4j.circuitbreaker.instances.referenceDataService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.referenceDataService.sliding-window-size=4
resilience4j.circuitbreaker.instances.referenceDataService.minimum-number-of-calls=4
resilience4j.circuitbreaker.instances.referenceDataService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.referenceDataService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.referenceDataService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.referenceDataService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.referenceDataService.record-exceptions=com.tradeflow.trade.exception.ReferenceDataServiceUnavailableException
resilience4j.circuitbreaker.instances.referenceDataService.ignore-exceptions=com.tradeflow.trade.exception.ReferenceDataClientException
